services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep uvicorn | grep -v grep || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3031:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    command: npm run dev

volumes:
  backend_data: 